FROM node:18.13-bullseye-slim AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

FROM node:18.13-alpine

WORKDIR /app

COPY --from=builder /app/build build

ENV PORT=8080

CMD [ "npx", "--yes", "serve", "build" ]