FROM node:18.13.0-bullseye-slim AS builder

WORKDIR /app

COPY . .

RUN npm run build

FROM node:18.13.0-alpine

WORKDIR /app

COPY --from=builder /app/build build

ENV PORT=8080

CMD [ "npx", "--yes", "serve", "build" ]